// Generated by CoffeeScript 1.7.1
(function() {
  var TicTacGame, game,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  TicTacGame = (function() {
    function TicTacGame(game) {
      this.game = game;
      this.update = __bind(this.update, this);
      this.setGameField = __bind(this.setGameField, this);
      this.updateMarker = __bind(this.updateMarker, this);
      this.createLines = __bind(this.createLines, this);
      this.create = __bind(this.create, this);
      this.preload = __bind(this.preload, this);
      this.ticTacModel = new TicTacToeGameModel(20);
    }

    TicTacGame.prototype.preload = function() {
      return this.game.load.image('tiles', 'tiles.png');
    };

    TicTacGame.prototype.create = function() {
      this.game.stage.backgroundColor = "#2d2d2d";
      this.createLines();
      this.map = this.game.add.tilemap();
      this.map.addTilesetImage('tiles');
      this.layer = this.map.create('level', this.ticTacModel.mapSize, this.ticTacModel.mapSize, 32, 32);
      this.layer.resizeWorld();
      this.game.input.setMoveCallback(this.updateMarker, this);
      this.cursors = this.game.input.keyboard.createCursorKeys();
      this.marker = this.game.add.graphics();
      this.marker.lineStyle(2, 0x000000, 1);
      this.marker.drawRect(0, 0, 32, 32);
      this.pointerMoved = false;
      this.game.camera.x = 25;
      return this.game.camera.y = 25;
    };

    TicTacGame.prototype.createLines = function() {
      var i, _i, _j, _ref, _ref1, _results;
      this.lines = this.game.add.graphics();
      this.lines.lineStyle(1, 0x00ff00, 1);
      for (i = _i = 1, _ref = this.ticTacModel.mapSize; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
        this.lines.moveTo(0, i * 32);
        this.lines.lineTo(this.ticTacModel.mapSize * 32, i * 32);
      }
      _results = [];
      for (i = _j = 1, _ref1 = this.ticTacModel.mapSize; 1 <= _ref1 ? _j <= _ref1 : _j >= _ref1; i = 1 <= _ref1 ? ++_j : --_j) {
        this.lines.moveTo(i * 32, 0);
        _results.push(this.lines.lineTo(i * 32, this.ticTacModel.mapSize * 32));
      }
      return _results;
    };

    TicTacGame.prototype.updateMarker = function() {
      var tileX, tileY;
      this.pointerMoved = true;
      this.marker.x = (this.layer.getTileX(game.input.activePointer.worldX)) * 32;
      this.marker.y = (this.layer.getTileY(game.input.activePointer.worldY)) * 32;
      tileX = this.layer.getTileX(this.marker.x);
      tileY = this.layer.getTileY(this.marker.y);
      if (this.game.input.mousePointer.isDown) {
        return this.setGameField(tileX, tileY);
      }
    };

    TicTacGame.prototype.setGameField = function(tileX, tileY) {
      if (this.ticTacModel.isMoveAllowed(tileX, tileY)) {
        this.ticTacModel.setField(tileX, tileY);
        return this.map.putTile(this.ticTacModel.getTileNumber(), tileX, tileY, this.layer);
      }
    };

    TicTacGame.prototype.update = function() {
      var tileX, tileY;
      tileX = this.layer.getTileX(this.marker.x);
      tileY = this.layer.getTileY(this.marker.y);
      if (this.pointerMoved) {
        this.cursorIsNearEdgeAction(tileX, tileY);
      }
      if (this.cursors.left.isDown) {
        return this.game.camera.x -= 4;
      } else if (this.cursors.right.isDown) {
        return this.game.camera.x += 4;
      } else if (this.cursors.up.isDown) {
        return this.game.camera.y -= 4;
      } else if (this.cursors.down.isDown) {
        return this.game.camera.y += 4;
      }
    };

    TicTacGame.prototype.cursorIsNearEdgeAction = function(tileX, tileY) {
      var endX, endY, startX, startY;
      startX = this.layer.getTileX(this.game.camera.x);
      startY = this.layer.getTileY(this.game.camera.y);
      endX = this.layer.getTileX(this.game.camera.x + this.game.camera.width);
      endY = this.layer.getTileY(this.game.camera.y + this.game.camera.height);
      if (tileX <= (startX + 2)) {
        this.game.camera.x -= 4;
      }
      if (tileX >= (endX - 2)) {
        this.game.camera.x += 4;
      }
      if (tileY <= (startY + 2)) {
        this.game.camera.y -= 4;
      }
      if (tileY >= (endY - 2)) {
        return this.game.camera.y += 4;
      }
    };

    return TicTacGame;

  })();

  game = new Phaser.Game(480, 480, Phaser.AUTO, 'phaser-target', new TicTacGame());

  this.game = game;

}).call(this);
