// Generated by CoffeeScript 1.7.1
(function() {
  var TicTacGame, game,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  TicTacGame = (function() {
    function TicTacGame(game) {
      var i, j;
      this.game = game;
      this.update = __bind(this.update, this);
      this.setGameField = __bind(this.setGameField, this);
      this.updateMarker = __bind(this.updateMarker, this);
      this.createLines = __bind(this.createLines, this);
      this.create = __bind(this.create, this);
      this.preload = __bind(this.preload, this);
      this.currentTile = 0;
      this.simpleGameState = (function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; _i <= 20; i = ++_i) {
          _results.push((function() {
            var _j, _results1;
            _results1 = [];
            for (j = _j = 0; _j <= 20; j = ++_j) {
              _results1.push(-1);
            }
            return _results1;
          })());
        }
        return _results;
      })();
      this.firstPlayer = true;
    }

    TicTacGame.prototype.preload = function() {
      return this.game.load.image('tiles', 'tiles.png');
    };

    TicTacGame.prototype.create = function() {
      this.game.stage.backgroundColor = "#2d2d2d";
      this.createLines();
      this.map = this.game.add.tilemap();
      this.map.addTilesetImage('tiles');
      this.layer = this.map.create('level', 20, 20, 32, 32);
      this.layer.resizeWorld();
      this.game.input.setMoveCallback(this.updateMarker, this);
      this.cursors = this.game.input.keyboard.createCursorKeys();
      this.marker = this.game.add.graphics();
      this.marker.lineStyle(2, 0x000000, 1);
      this.marker.drawRect(0, 0, 32, 32);
      this.pointerMoved = false;
      this.game.camera.x = 25;
      return this.game.camera.y = 25;
    };

    TicTacGame.prototype.createLines = function() {
      var i, _i, _j, _results;
      this.lines = this.game.add.graphics();
      this.lines.lineStyle(1, 0x00ff00, 1);
      for (i = _i = 1; _i <= 19; i = ++_i) {
        this.lines.moveTo(0, i * 32);
        this.lines.lineTo(20 * 32, i * 32);
      }
      _results = [];
      for (i = _j = 1; _j <= 19; i = ++_j) {
        this.lines.moveTo(i * 32, 0);
        _results.push(this.lines.lineTo(i * 32, 20 * 32));
      }
      return _results;
    };

    TicTacGame.prototype.updateMarker = function() {
      var tileX, tileY;
      this.pointerMoved = true;
      this.marker.x = (this.layer.getTileX(game.input.activePointer.worldX)) * 32;
      this.marker.y = (this.layer.getTileY(game.input.activePointer.worldY)) * 32;
      tileX = this.layer.getTileX(this.marker.x);
      tileY = this.layer.getTileY(this.marker.y);
      if (this.game.input.mousePointer.isDown) {
        return this.setGameField(tileX, tileY);
      }
    };

    TicTacGame.prototype.setGameField = function(tileX, tileY) {
      var currentTile;
      if (this.simpleGameState[tileX][tileY] === -1) {
        currentTile = this.firstPlayer ? 0 : 1;
        this.firstPlayer = !this.firstPlayer;
        this.map.putTile(currentTile, tileX, tileY, this.layer);
        return this.simpleGameState[tileX][tileY] = currentTile;
      }
    };

    TicTacGame.prototype.update = function() {
      var tileX, tileY;
      tileX = this.layer.getTileX(this.marker.x);
      tileY = this.layer.getTileY(this.marker.y);
      if (this.pointerMoved) {
        this.cursorIsNearEdgeAction(tileX, tileY);
      }
      if (this.cursors.left.isDown) {
        return this.game.camera.x -= 4;
      } else if (this.cursors.right.isDown) {
        return this.game.camera.x += 4;
      } else if (this.cursors.up.isDown) {
        return this.game.camera.y -= 4;
      } else if (this.cursors.down.isDown) {
        return this.game.camera.y += 4;
      }
    };

    TicTacGame.prototype.cursorIsNearEdgeAction = function(tileX, tileY) {
      var endX, endY, startX, startY;
      startX = this.layer.getTileX(this.game.camera.x);
      startY = this.layer.getTileY(this.game.camera.y);
      endX = this.layer.getTileX(this.game.camera.x + this.game.camera.width);
      endY = this.layer.getTileY(this.game.camera.y + this.game.camera.height);
      if (tileX <= (startX + 2)) {
        this.game.camera.x -= 4;
      }
      if (tileX >= (endX - 2)) {
        this.game.camera.x += 4;
      }
      if (tileY <= (startY + 2)) {
        this.game.camera.y -= 4;
      }
      if (tileY >= (endY - 2)) {
        return this.game.camera.y += 4;
      }
    };

    return TicTacGame;

  })();

  game = new Phaser.Game(480, 480, Phaser.AUTO, 'phaser-target', new TicTacGame());

  this.game = game;

}).call(this);
