// Generated by CoffeeScript 1.7.1
(function() {
  this.TicTacToeGameModel = (function() {
    function TicTacToeGameModel(mapSize) {
      var i, j;
      this.mapSize = mapSize != null ? mapSize : 20;
      this.stage = (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = mapSize - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          _results.push((function() {
            var _j, _ref1, _results1;
            _results1 = [];
            for (j = _j = 0, _ref1 = mapSize - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; j = 0 <= _ref1 ? ++_j : --_j) {
              _results1.push(-1);
            }
            return _results1;
          })());
        }
        return _results;
      })();
      this.firstPlayer = true;
      this.lastMove = {
        x: Math.round(mapSize / 2),
        y: Math.round(mapSize / 2)
      };
    }

    TicTacToeGameModel.prototype.isMoveAllowed = function(tileX, tileY) {
      return (this.isWithinStageBounds(tileX, tileY)) && this.stage[tileX][tileY] === -1;
    };

    TicTacToeGameModel.prototype.isWithinStageBounds = function(tileX, tileY) {
      return tileX >= 0 && tileY >= 0 && tileX < this.mapSize && tileY < this.mapSize;
    };

    TicTacToeGameModel.prototype.setField = function(tileX, tileY) {
      this.stage[tileX][tileY] = this.firstPlayer ? 0 : 1;
      this.firstPlayer = !this.firstPlayer;
      return this.lastMove = {
        x: tileX,
        y: tileY
      };
    };

    TicTacToeGameModel.prototype.getTileNumber = function() {
      if (this.firstPlayer) {
        return 0;
      } else {
        return 1;
      }
    };

    TicTacToeGameModel.prototype.didGameEnded = function() {
      var direction, directions, player, _i, _len;
      directions = this._getAllDirections();
      player = this.stage[this.lastMove.x][this.lastMove.y];
      if (player === -1) {
        player = 0;
      }
      for (_i = 0, _len = directions.length; _i < _len; _i++) {
        direction = directions[_i];
        if (this._checkDirection(direction, player)) {
          return {
            finished: true,
            player: player
          };
        }
      }
      return {
        finished: false,
        player: player
      };
    };

    TicTacToeGameModel.prototype._checkDirection = function(direction, player) {
      var field, ok, _i, _len;
      ok = true;
      for (_i = 0, _len = direction.length; _i < _len; _i++) {
        field = direction[_i];
        ok = ok && field === player;
      }
      return ok;
    };

    TicTacToeGameModel.prototype._getAllDirections = function() {
      var changer, dirChangers, _i, _len, _results;
      dirChangers = this.createDirectionChangers();
      _results = [];
      for (_i = 0, _len = dirChangers.length; _i < _len; _i++) {
        changer = dirChangers[_i];
        _results.push(this.getDirection(this.lastMove.x, this.lastMove.y, changer[0], changer[1]));
      }
      return _results;
    };

    TicTacToeGameModel.prototype.createDirectionChangers = function() {
      var changers, i, j, _i, _j;
      changers = [];
      for (i = _i = -1; _i <= 1; i = ++_i) {
        for (j = _j = -1; _j <= 1; j = ++_j) {
          if (i !== 0 || j !== 0) {
            changers.push([i, j]);
          }
        }
      }
      return changers;
    };

    TicTacToeGameModel.prototype.getDirection = function(x, y, dirX, dirY) {
      var fields, i, _i;
      fields = [];
      for (i = _i = 0; _i <= 4; i = ++_i) {
        if (this.isWithinStageBounds(x, y)) {
          fields.push(this.stage[x][y]);
        }
        x += dirX;
        y += dirY;
      }
      return fields;
    };

    return TicTacToeGameModel;

  })();

}).call(this);
