// Generated by CoffeeScript 1.7.1
(function() {
  describe('TicTacToeGameModel', function() {
    beforeEach(function() {
      return this.model = new TicTacToeGameModel(20);
    });
    return it('getDirection works correctly', function() {
      var fields;
      this.model.stage[10][10] = 1;
      this.model.stage[10][11] = 0;
      fields = this.model.getDirection(10, 9, 0, 1);
      expect(fields).toEqual([-1, 1, 0, -1, -1]);
      fields = this.model.getDirection(10, 12, 0, -1);
      expect(fields).toEqual([-1, 0, 1, -1, -1]);
      fields = this.model.getDirection(9, 10, 1, 0);
      expect(fields).toEqual([-1, 1, -1, -1, -1]);
      fields = this.model.getDirection(11, 10, -1, 0);
      expect(fields).toEqual([-1, 1, -1, -1, -1]);
      fields = this.model.getDirection(9, 9, 1, 1);
      expect(fields).toEqual([-1, 1, -1, -1, -1]);
      fields = this.model.getDirection(11, 11, -1, -1);
      expect(fields).toEqual([-1, 1, -1, -1, -1]);
      fields = this.model.getDirection(11, 9, -1, 1);
      expect(fields).toEqual([-1, 1, -1, -1, -1]);
      fields = this.model.getDirection(9, 11, 1, -1);
      return expect(fields).toEqual([-1, 1, -1, -1, -1]);
    });
  });

}).call(this);
